$background  =            rgb(%%color0%%)
$selection_foreground =    rgb(%%color15%%)
$selection_background  =  rgb(%%color8%%)
$url_color              = rgb(%%color4%%)

$color0  =  rgb(%%color0%%)
$color8  =  rgb(%%color8%%)
$color1  =  rgb(%%color1%%)
$color9  =  rgb(%%color9%%)
$color2  =  rgb(%%color2%%)
$color10 =  rgb(%%color10%%)
$color3  =  rgb(%%color3%%)
$color11 =  rgb(%%color11%%)
$color4  =  rgb(%%color4%%)
$color12 =  rgb(%%color12%%)
$color5  =  rgb(%%color5%%)
$color13 =  rgb(%%color13%%)
$color6  =  rgb(%%color6%%)
$color14 =  rgb(%%color14%%)
$color7  =  rgb(%%color7%%)
$color15 =  rgb(%%color15%%)
